### ISSUE TITLE
Potsdam and Vaihingen datasets have not apply RandomVerticalFlip

### ISSUE THREAD

**Issue by starsky0426** [lxtGH/PFSegNets#14]
The code contains many interesting data augmentation, such as bblur, gblur, although they seem to be not used.

In `datasets/__init__.py`, only iSAID dataset applied RandomVerticalFlip, is there any specific reason that Potsdam and Vaihingen do not applied this data augmentation?

**Comment by lxtGH** [comment]
We perform this operation only on ISAID. However, if you apply this operation. It maybe result in better results.
