### ISSUE TITLE
Test miou 62.79% on iSAID with your provided model

### ISSUE THREAD

**Issue by qixiong-wang** [lxtGH/PFSegNets#16]
Hello,I download your model checkpoints, and use the command to run code.
`sh scripts/pointflow/test/test_iSAID_pfnet_R50.sh pfnet_r50_iSAID.pth ./
`

04-17 22:06:28.503 IoU:
04-17 22:06:28.504 label_id      label    iU    Precision Recall TP     FP    FN
04-17 22:06:28.504  0       background   97.92   0.99      0.99  92.76    0.01    0.01
04-17 22:06:28.504  1             ship   61.21   0.73      0.79   0.44    0.37    0.26
04-17 22:06:28.504  2       store_tank   53.22   0.62      0.79   0.04    0.61    0.26
04-17 22:06:28.504  3    baseball_diamond   82.93   0.89      0.92   0.22    0.12    0.08
04-17 22:06:28.504  4     tennis_court   89.68   0.94      0.95   1.42    0.07    0.05
04-17 22:06:28.504  5    basketball_court   69.35   0.83      0.81   0.15    0.20    0.24
04-17 22:06:28.504  6    Ground_Track_Field   50.21   0.57      0.82   0.23    0.77    0.22
04-17 22:06:28.504  7           Bridge   40.72   0.53      0.64   0.02    0.89    0.57
04-17 22:06:28.504  8    Large_Vehicle   67.97   0.80      0.82   0.77    0.25    0.22
04-17 22:06:28.504  9    Small_Vehicle   44.52   0.50      0.80   0.33    1.00    0.25
04-17 22:06:28.504 10       Helicopter   17.25   0.18      0.75   0.00    4.47    0.33
04-17 22:06:28.504 11    Swimming_pool   55.60   0.62      0.84   0.03    0.61    0.19
04-17 22:06:28.504 12       Roundabout   84.32   0.91      0.92   0.06    0.10    0.08
04-17 22:06:28.504 13    Soccer_ball_field   66.42   0.75      0.86   0.65    0.34    0.17
04-17 22:06:28.504 14            plane   67.02   0.81      0.80   0.17    0.24    0.25
04-17 22:06:28.504 15           Harbor   56.34   0.70      0.74   0.51    0.43    0.34
04-17 22:06:28.505 mean iou 0.6279170544427546
04-17 22:06:28.505 all acc: 0.9778778046255348
04-17 22:06:28.505 macc:0.7102180467377563

Is there anything wrong?

**Comment by lxtGH** [comment]
https://github.com/lxtGH/PFSegNets/issues/5 Please refer this.
