### ISSUE TITLE
Error: No module named 'network.deepv3'

### ISSUE THREAD

**Issue by kangkanghe** [lxtGH/PFSegNets#18]
这一步的目的是什么：
# Argument Parser
parser.add_argument('--arch', type=str, default='network.deepv3.DeepWV3Plus', help='Network architecture. We have DeepSRNX50V3PlusD (backbone: ResNeXt50) \ and deepWV3Plus (backbone: WideResNet38).')

为什么显示ModuleNotFoundError: No module named 'network.deepv3'错误

**Comment by lxtGH** [comment]
hi 这个地下需要根据你的model 来选择对应py文件
