### ISSUE TITLE
Bug feedback

### ISSUE THREAD

**Issue by purse1996** [lxtGH/PFSegNets#4]
Good job!
While there seem to exist a bug in iSAID.py: 

 @staticmethod
    def get_boundary(mask, thicky=8):
        tmp = mask.data.numpy().astype('uint8')
        # import pdb
        # pdb.set_trace()
        # print(tmp.dtype())
        contour, _ = cv2.findContours(tmp, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

        boundary = np.zeros_like(tmp)
        boundary = cv2.drawContours(boundary, contour, -1, 1, thicky)
        boundary = boundary.astype(np.float)
        return boundary

‘Mask’ is a gray image, while cv2.findContours requires the input image is the binary image. So the code can not run.

Another question: What does 'boundary' mean?  Boundary or Boundary attached to the label image?

**Comment by purse1996** [comment]
opencv version

**Comment by shanshanwang28** [comment]
which opencv version is right？ thanks

**Comment by shanshanwang28** [comment]
which version is right？thank you very much！
