### ISSUE TITLE
About overlap_area=200 in patch plit on validatin set

### ISSUE THREAD

**Issue by slacklife** [lxtGH/PFSegNets#6]
I found the `overlap_area=200` in default in [split_iSAID.py](https://github.com/lxtGH/PFSegNets/blob/master/tools/split_iSAID.py#L19)
The overlap is benefit in training phase.
However, how about the overlap_area in testing phase on validate set.
I think that if there is overlap in the testing phase, the prediction of overlap area a need to be merged.

Does the patch split on validate set in this paper have overlap_area=200 ?

**Comment by purse1996** [comment]
Mark! 
Similarity problem, how to evaluate mIoU on testing phase.

**Comment by dongbo811** [comment]
I have the question.
BTW, the miou seems to include the backgroud. 
It's right?

**Comment by lxtGH** [comment]
@slacklife We follow the same pre-processing for training and validation set. @dongbo811 Yes the mIoU contains the background and this is the same setting with FarSeg.
